export function shellQuote(value) {
  const text = String(value ?? '');
  if (text.length === 0) {
    return "''";
  }
  return `'${text.replaceAll("'", "'\"'\"'")}'`;
}

export function generateManagedZsh(config) {
  const lines = [
    '# Generated by zsh Config Center.',
    '# Edit from the local web app instead of changing this file by hand.',
    '# Source: ~/.config/zsh-config/config.json',
    '',
    'typeset -g ZSH_CONFIG_MANAGED_LOADED=1',
    ''
  ];

  lines.push('# --- Aliases --------------------------------------------------------------');
  const aliases = config.aliases.filter((item) => item.enabled && item.name && item.command);
  if (aliases.length === 0) {
    lines.push('# No managed aliases.');
  } else {
    for (const alias of aliases) {
      if (alias.description) {
        lines.push(`# ${safeComment(alias.description)}`);
      }
      lines.push(`alias ${alias.name}=${shellQuote(alias.command)}`);
    }
  }

  lines.push('', '# --- PATH -----------------------------------------------------------------');
  const pathEntries = config.paths.filter((item) => item.enabled && item.value);
  if (pathEntries.length === 0) {
    lines.push('# No managed PATH entries.');
  } else {
    lines.push('_zsh_config_add_path() {');
    lines.push('  local mode="$1"');
    lines.push('  local entry="$2"');
    lines.push('  [[ -n "$entry" ]] || return 0');
    lines.push('  case ":$PATH:" in');
    lines.push('    *":$entry:"*) return 0 ;;');
    lines.push('  esac');
    lines.push('  if [[ "$mode" == "append" ]]; then');
    lines.push('    export PATH="$PATH:$entry"');
    lines.push('  else');
    lines.push('    export PATH="$entry:$PATH"');
    lines.push('  fi');
    lines.push('}');
    for (const entry of pathEntries) {
      if (entry.description) {
        lines.push(`# ${safeComment(entry.description)}`);
      }
      lines.push(`_zsh_config_add_path ${shellQuote(entry.position)} ${shellQuote(entry.value)}`);
    }
    lines.push('unfunction _zsh_config_add_path 2>/dev/null || true');
  }

  lines.push('', '# --- Environment ----------------------------------------------------------');
  const envEntries = config.env.filter((item) => item.enabled && item.key);
  if (envEntries.length === 0) {
    lines.push('# No managed environment variables.');
  } else {
    for (const item of envEntries) {
      if (item.description) {
        lines.push(`# ${safeComment(item.description)}`);
      }
      const prefix = item.exported ? 'export ' : '';
      lines.push(`${prefix}${item.key}=${shellQuote(item.value)}`);
    }
  }

  lines.push('', '# --- Oh My Zsh ------------------------------------------------------------');
  lines.push('# These values are emitted for visibility. If this file is sourced after');
  lines.push('# oh-my-zsh has already loaded, theme/plugin changes need a new bootstrap');
  lines.push('# position before `source $ZSH/oh-my-zsh.sh` to affect startup behavior.');
  if (config.ohMyZsh.theme.enabled && config.ohMyZsh.theme.value) {
    lines.push(`ZSH_THEME=${shellQuote(config.ohMyZsh.theme.value)}`);
  } else {
    lines.push('# No managed ZSH_THEME override.');
  }
  if (config.ohMyZsh.plugins.enabled && config.ohMyZsh.plugins.values.length > 0) {
    lines.push(`plugins=(${config.ohMyZsh.plugins.values.map(shellQuote).join(' ')})`);
  } else {
    lines.push('# No managed oh-my-zsh plugin override.');
  }

  lines.push('');
  return `${lines.join('\n')}\n`;
}

function safeComment(value) {
  return String(value).replaceAll('\n', ' ').replaceAll('\r', ' ').replaceAll('`', "'");
}
