import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { bootstrap } from '../src/server.js';
import { bootstrapSourceLine, getPaths } from '../src/paths.js';

test('bootstrap creates managed files and appends source line once', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'zsh-config-test-'));
  const home = path.join(root, 'home');
  await fs.mkdir(home, { recursive: true });
  const zshrc = path.join(home, '.zshrc');
  await fs.writeFile(zshrc, 'export ZSH="$HOME/.oh-my-zsh"\n', 'utf8');
  const paths = getPaths({
    HOME: home,
    ZSH_CONFIG_HOME: path.join(home, '.config', 'zsh-config'),
    ZSH_CONFIG_ZSHRC: zshrc,
    ZSH_CONFIG_ZPROFILE: path.join(home, '.zprofile'),
    ZSH_CONFIG_ZSHENV: path.join(home, '.zshenv'),
    ZSH_CONFIG_OMZ_CUSTOM: path.join(home, '.oh-my-zsh', 'custom')
  });

  await bootstrap(paths);
  await bootstrap(paths);

  const content = await fs.readFile(zshrc, 'utf8');
  assert.equal(content.split(bootstrapSourceLine()).length - 1, 1);
  assert.match(await fs.readFile(paths.managedFile, 'utf8'), /Generated by zsh Config Center/);
  assert.ok((await fs.readdir(paths.backupsDir)).length >= 1);
});
